### ISSUE TITLE
App doesn't work on non-SSE2 processors

### ISSUE THREAD

**Issue by bucanero** [antikmozib/AM-Downloader#21]
**Describe the bug**

Even though the Readme says that the app requires Win7 SP1, it actually requires processors with SSE2 too (for example Pentium 4 and up)

I know it's not common, but I have a Win7 SP1 system running an Athlon XP (2 GHz) CPU and it doesn't have SSE2, so the app fails to start. 

**Expected behavior**
I expected the app to run correctly, or at least have a note on the ReadMe about the additional requirements.

I know it's not the developer fault, I think that Visual Studio since 2013 auto-compiles things with SSE2 by default, so unless it's explicit built with SSE2 disabled, any binary will fail to run on processors like AMD Athlon XP, or Intel Pentium 3.

**Version (please complete the following information):**
 - Windows version: Windows 7 SP1 (32 bits)
 - AM Downloader version: latest version

**Comment by trivalik** [comment]
I installed just for fun Windows 7 SP1 x86 in QEMU. Here I set up the CPU to pentium 3 to get rid of SSE2 instruction set.
Then install .NET6 in version 6.0.36. That this could run you have to follow https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore2x#windows-7--81--server-2012 (install VC Redist and KB3063858), but for some reason I end up in another error 0xC0000005 executing AM-Downloader version 1.3.3.0. Is that the error what you saw?

What I found also was running `dotnet run` endup in `TypeInitializerException` in `TimeZoneInfo.cctor`.

BTW The newest version does only support .NET 8, means Windows 7 SP1 is out of support.

---------------------------------------

Here steps of installation Windows 7 in QEMU for my future me (I used QEMU in a VM :-) ):
```
C:\Users\admin\Downloads>"C:\Program Files\qemu\qemu-img.exe" create -f qcow2 w7.qcow2 40G
"C:/Program Files/qemu/qemu-system-x86_64.exe" -m 1024 -smp 1 -k ich9-usb-echi1 -hda "C:/Users/admin/Downloads/w7.qcow2" -M pc -cpu pentium3 -net nic,model=e1000 -net user -cdrom "C:/Users/admin/Desktop/de_windows_7_professional_with_sp1_x86_dvd_u_677093.iso"
```

Future runs of QEMU was then with another iso to transfer all kind of programs to the virtual machine. I used ImgBurn to create the iso from files.

**Comment by bucanero** [comment]
> but for some reason I end up in another error 0xC0000005 executing AM-Downloader version 1.3.3.0. Is that the error what you saw?
> 

yes, that's the error, and it happens with any app or tool that requires SSE2 instructions. My guess is that some .Net library or compiler used to build AM-Downloader requires SSE2 and that's why the error shows up.

(for example this problem also happens with many Win7 updates from Microsoft after 2017, because they started building and compiling with SSE2 enabled and all those updates will crash your system. It can even brick a working Win7 SP1 setup and unless you have a restore point your system will be unable to boot)

**Comment by trivalik** [comment]
I compiled my own old version of AM Downloader and copied over and run it on Windows 7 SP1 x86. It ends up with another error code `0xe0434352`. Which means nothing: https://stackoverflow.com/questions/6244939/how-do-i-fix-a-net-windows-application-crashing-at-startup-with-exception-code
So I created a dump and loaded it in VS 2022.

```
at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Return(T[] array, Boolean clearArray) in System.Buffers\TlsOverPerCoreLockedStacksArrayPool.cs:line 309
   at System.IO.BinaryWriter.Write(String value) in System.IO\BinaryWriter.cs:line 316
   at System.Security.IdentityHelper.GetStrongHashSuitableForObjectName(String name)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(String exePath, Boolean isSingleFile)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.Internal.ConfigurationManagerInternal.System.Configuration.Internal.IConfigurationManagerInternal.get_ExeProductName()
   at System.Configuration.ApplicationSettingsBase.get_Initializer()
   at System.Configuration.ApplicationSettingsBase.CreateSetting(PropertyInfo propertyInfo)
   at System.Configuration.ApplicationSettingsBase.EnsureInitialized()
   at System.Configuration.ApplicationSettingsBase.get_Properties()
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at AMDownloader.Properties.Settings.get_LaunchCount()
   at AMDownloader.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Threading\ExecutionContext.cs:line 137
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Threading\ExecutionContext.cs:line 152
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Threading\ExecutionContext.cs:line 113
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at AMDownloader.App.Main()
```
